### PR TITLE
Modify README.md

### PR DESCRIPTION
**Pull request by BJReplay**
- Altered instructions to improve setting up docker - updated keys for docker repository using instructions from https://docs.docker.com/engine/install/ubuntu/
- Changed instructions from getting entire mastodon git repository to getting just the docker-compose yaml
- Change from using docker-compose to docker compose
- Add suggestion to retry if first docker compose fails

### CODE REVIEW

**Comment by BJReplay** [comment]
Thanks for your guide - incredibly helpful.  The least I could do was update it with a couple of things I ran into while using it!

Docker didn't install properly for me, and I ended up blowing away the entire image and starting again.  

When I did, I figured all I needed was the docker-compose.yml from the mastodon git repo.

**Comment by EasternPA** [comment]
Thanks very much for your feedback and PR. I never thought anyone would find this :)

As for the Dockerfile error, it fails because you never replicated it in the wget. You may wish to run `touch Dockerfile` to create an empty one and satisfy the request. Also, I think the flow is failing because the service definitions in docker-compose.yml contain the `Build: .` line. If you don't `touch Dockerfile` to create one, I bet you could comment out the `Build: .` lines in the services that have it. I'm thinking that making that change will prevent the startup process from looking for that file. If there's no Build command, it shouldn't look for the Dockerfile.

Are you willing to follow the process again, making either or both of those changes (one at a time, of course, never break the golden rule of troubleshooting) and then update your PR accordingly? `touch Dockerfile` is obviously the less intrusive change and would probably be enough. It also allows you to leave the docker-compose.yml intact. Yes, you can run it twice to get through it, but its always better to aim for no errors on run-through, no?

**Comment by BJReplay** [comment]
Hmm, interesting - I think I got the dockerfile error even when I did the full git pull on my first attempts - but I've done that many, I can't be certain.
And you're right - I didn't comment out the build lines - that was an oversight for the change that I made to only get the file.

I found this because I've tried so many times to get this going.  I'm not sure why it was failing but I could never successfully get the mastodon website up behind NPM.  Because I've already tried so many times, I am willing to do this again - I've done about 10 attempts in total, including trying to stand up my own home automation server (not bare metal - WSL already hosting several other things on docker successfully including NPM), as well as azure and oracle cloud.

There's another missing step which is opening up ingress on your oracle cloud instance for 443 which caused me no end of grief - I couldn't connect to the instance even when it came up.  That had the same symptoms that I was experiencing on my home server as well (and I know I didn't have that ingress problem because I could connect to NPM from the outside world - that was already working) - timeout connecting to main mastodon URL.

Yeah, let me stand up another instance and run through it again, and see if can modify - I'm tempted to suggest editing the dockerfile and commenting the build lines.

Finally, the other thing I did was add in a location for streaming in the NPM proxy definition - not sure if needed, but I assume it is if you want to serve streaming :)

**Comment by EasternPA** [comment]
Thank you, @BJReplay, for the additional comments, I appreciate it. If you go back through the commit history, just about every commit represents a time when I started over from the beginning :smile: . I don't remember opening the ingress on the cloud instance, but that was so many rebuilds ago I'm not surprised.  I have blown away and started fresh with a new instance, too, not just blowing away the docker-compose stack, so that ingress seems to be at the account level (?). Either way, I appreciate you pointing it out. If I did it, I only did it once and lost track of that with the dozens of rebuilds.

Also, check out the CF instructions in this repo. I worked those out when installing them at home and using Cloudflare tunnels. I can tell you, those instructions are nowhere _near_ as clean as these, however. If you made it through these instructions and arrived at a working config, you'll be fine with the CF instructions for sure. Either way, it results in a working build at home, and you don't have to worry about port forwarding or the NPM piece. CF handles all that for you with the tunnel.

I can also tell you that I am starting to run into space issues with the build you are helping me clean up. I'm running Matrix on another arm instance, and while you can't choose the amount of disk space allocated to each instance, my Mastodon instance was only given 45 GB. I thought that would be enough, but I've been running perilously low for a while and down to 0 bytes free for a day and a half. I lowered my media retention to just a day or two, but I went nuts following close to 700 people. Caching all that data just wrecked the disk allocation. I lowered all retention limits to 1 day and unfollowed over 200 people today when I saw that their instances allow public access to their local timeline. I subscribed to the RSS feed instead of following every person I could find on that server.

So if you want to have an unhindered experience, definitely check out my CF build. I don't want to run this on my home LAN until I establish a DMZ, so I have not migrated yet. I appreciate your willingness to help here, and I'm happy to put out some good build instructions to help people get a taste of what it's like before needing to spend any money (well, more than $11).

**Comment by BJReplay** [comment]
For some reason, the last two edits I made have resulted in conflicts, which is really annoying.

Anyway, long story short...

1. You can change all docker-compose commands to docker compose - and it just works.  Don't change all docker-compose though - the file name obviously must remain docker-compose.yml.
2. You're right - commenting out the build . lines fixed that error.
3. I'll try to get a pull request that doesn't have conflicts, but if I can't I'll thank you for your guide!

**Comment by EasternPA** [comment]
I'll make the merge work. Did you try to `touch Dockerfile` to see if that fixed it, too? I'd rather not edit the docker-compose.yml if a simple `touch` will clear it up.

**Comment by BJReplay** [comment]
I did not, sorry.  I probably should have, but didn't try that approach. 

If I stand up another instance, I'll get back to you!

**Comment by EasternPA** [comment]
Thank you for writing up the Ingress rule steps. I moved them out of the middle of the docker install steps and placed them right after the VPS creation steps.

**Comment by BJReplay** [comment]
Yeah, that makes sense.  I put them there logically (at least in my mind) because they came after the firewall rules were set up, but it makes more sense the way you've done it, and the risk surface for something you're in the process of setting up with nothing actually listening on 443 is near enough to zero anyway.

**Comment by BJReplay** [comment]
> I did not, sorry. I probably should have, but didn't try that approach.
> 
> If I stand up another instance, I'll get back to you!

Well, I am standing up a new instance, because I'm moving off a subdomain to the main domain.

touching Dockerfile isnt enough:

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: the Dockerfile cannot be empty`

**Comment by EasternPA** [comment]
Thank you for following up on this. I set this to primary but will reverse
it when I get up in the morning now that we know it isn't enough.

Thanks again and thanks for opening this avenue of investigation.

**Pull request merged**
